hashrocket/tilex

package.json

Ultimately I think we should move away from brunch and use Webpack which is what we all love and know but in the meantime let's add brunch to the package.json as long as it's being used

Add brunch to npm devDependencies

---

.env.example
.gitignore
README.md
config/config.exs
mix.exs
mix.lock
web/controllers/auth_controller.ex
web/router.ex

This provides the ability to sign in via Google Oauth, and adds environmental variables.
The task isn't finished. We still need to create a developer model, and then make or load a developer record based on the payload returned from Google, as well as test the sign up/sign in flow.

Sign in via Google Auth

---

.projections.json

Latest version of vim-projectionist changes the behavior of `camelcase`.
To get the mixed case behavior we are looking for going forward, we need
to use `camelcase|capitalize`. This is backwards compatible with older
versions of vim-projectionist.
Here is the relevant issue:
https://github.com/tpope/vim-projectionist/pull/67#issuecomment-282513228

Fix projections for latest vim-projectionist

---

.gitignore
.projections.json
lib/tilex/posts.ex
priv/repo/migrations/20170319161606_add_developer_id_to_posts.exs
priv/repo/seeds.exs
test/features/developer_creates_post_test.exs
test/features/visitor_views_post_test.exs
test/models/post_test.exs
test/support/factory.ex
web/controllers/post_controller.ex
web/models/developer.ex
web/models/post.ex
web/templates/shared/_posts_list.html.eex
web/templates/shared/post.html.eex

This adds the developer's username to the post partial, which requires finishing the association between posts and developers. Doing so breaks the create post integration tests, because we don't yet have a way of identifying who the current developer is, which is required for a valid post changeset.
I've marked those two tests 'pending' and plan to remove that tag ASAP.

Add developer username

---

lib/tilex/integrations.ex
web/controllers/post_controller.ex

I have some thoughts on moving the Integration notification system out into its own little "umbrella" if/when we decide to convert to the new Phoenix 1.3 file structure. This is kind of the start of those thoughts. 
So now instead of having a bunch of functions like `post_notifications` and `post_likes` we can just have a generic `notify` and using pattern matching, send it anything we want. It will match and react to what we want, and ignore anything else. 
I also removed a couple module attribute definitions that were leftover from an earlier refactoring.

Integration is open for more than Post and remove unused module attributes

---

test/controllers/post_controller_test.exs
test/features/developer_edits_post_test.exs
web/controllers/post_controller.ex
web/router.ex
web/templates/post/edit.html.eex
web/templates/post/form.html.eex
web/templates/post/new.html.eex
web/templates/shared/post.html.eex

This completes the developer editing post story. 
I would have liked to pattern match the binary to the param directly for slug extraction, like:
```elixir
def show(conn, %{titled-slug => <<slug::size(10)-binary, _bla::binary>>}) do
#all the things
end
```
However, this led to the scenario of "what happens when someone visits an invalid URL with less than 10 characters?". Now there wouldn't be a function that would match... So you would have to write catch alls for all actions you match the binary on (show, edit, update):
```elixir
def show(conn, _params) do
#render 404
end
```
Thats a bummer. Assigning it to the conn doesn't feel too bad but I wish there was a better way. Maybe I'll think of something.

Developer edits post

---

lib/tilex/posts.ex
test/features/visitor_searches_posts.exs
test/support/test_helpers.ex
web/channels/post_channel.ex
web/templates/post/search_results.html.eex

I removed a lot of duplicate queries in `lib/tilex/posts.ex`, fixed some wallaby deprecations and fixed the search post feature.
TODO: Currently we can't paginate query responses because of a few reasons. 1 being that channels have no knowledge of conn. I think its an easy fix of just appending the page and query to the URL using the sockets response and then figuring out an elegant way to set `request_path` to the right URL for the `_pagination.html.eex` template. Either way searching currently works and pagination can be added at a later date.

Fix search

---

mix.exs

I've experienced tons of PhantomJS processes getting spun up when running the development server. Adding the `only: test` to `wallaby` resolved this for me. Regardless, this should be a test-only dependency.

Make the wallaby package test only

---

priv/repo/migrations/20170602200233_add_editor_to_developers.exs
test/features/developer_edits_profile_test.exs
web/models/developer.ex
web/templates/developer/edit.html.eex

Also cleans up Slack name concept, which we have decided to icebox for now.

Add editor to developer form

---

web/controllers/post_controller.ex
web/models/developer.ex

Going to the edit page when not authenticated caused a runtime exception instead of the expected response of going to index and displaying 'Authentication Required'.

Ensure auth on edit and update

---

web/views/layout_view.ex

One of the things I discovered at ElixirConf EU is that Map lookups are fairly slow in Elixir (unexpected because in Ruby hash lookups are fairly fast). I don't feel like it decreases the readability of `page_title` and with some benchmarking using a large Map like assigns, the `Map.get` conditional would often be around ~2.9 timex slower: 
```
Name                     ips        average  deviation         median
page_title           25.01 M      0.0400 μs    ±44.55%      0.0400 μs
page_title_map        8.83 M       0.113 μs   ±161.15%       0.100 μs
Comparison:
page_title           25.01 M
page_title_map        8.83 M - 2.83x slower
```
```
Name                     ips        average  deviation         median
page_title           25.15 M      0.0398 μs    ±48.61%      0.0400 μs …
```

Page title uses pattern matching

---

README.md

Confusingly, the badge was green in the readme when
the green pr had yet to be merged.

Travis badge should point to master

---

test/features/visitor_searches_posts_test.exs
test/support/pages/post_show_page.ex
web/templates/shared/post.html.eex

Remove #post_show id.  This id was being repeated for each post on the screen.

Remove #post_show id

---

test/features/visitor_views_channel_test.exs
test/features/visitor_views_developer_test.exs
test/features/visitor_views_post_test.exs
web/controllers/stats_controller.ex
web/templates/layout/app.html.eex
web/views/layout_view.ex

Page Titles are a significant SEO factor.  We had included the
organization name "Hashrocket" into the page title to try to
differentiate our "Today I Learned" site from the others, but this
was an experiment rather than a solution.  With the tilex deployment
it was likely the wrong time to make that experiment.
In addition, according to the search console help:
https://support.google.com/webmasters/answer/35624?visit_id=1-636351220308427108-3910826740&rd=1
Branding is encouraged but boilerplate is discouraged.  It's unclear if
the Hashrocket part of "Today I Learned - Hashrocket" would be
interpreted as branding or as something different.
Conciseness is encouraged as well, therefore this commit reverts to a
page title style that is simpler and more like what we had previously in
the …

Simplify page titles

---

web/controllers/stats_controller.ex
web/templates/stats/index.html.eex

Links now use the full sluggified URL
Fixes #87

Links use full post slug from stats page

---

package.json
web/static/js/post_form.js

Fixes #65 
It should now auto-expand (similar to how hr-til worked). I didn't check in the `/priv/static/*` files that will need to be included due to https://github.com/hashrocket/tilex/commit/39fad765a21b25bba282b07691a14f9a3eef91d5 . I'm using NPM version 3.10.10 and there were other changes made in some of the other js files probably due to differing versions? 
@jwworth How should I handle this? Should I just check in the `/priv` files my version spits out?

Auto resize post form body

---

web/controllers/api/developer_post_controller.ex
web/views/api/developer_post_view.ex
web/views/api/post_view.ex

I noticed we had a warning:
```terminal
warning: unused alias Post
web/controllers/api/developer_post_controller.ex:4
```
So I removed that. 
I also changed how we render the post JSON to use the more standard Phoenix convention of `render_many/3`. Open to suggestions but that seems to be the way most Phoenix apps are doing it.

Developer post api

---

lib/tilex/web/templates/layout/app.html.eex

I had left the hardcoded "https://til.hashrocket.com" in the twittercard.png URL because I didn't want to risk breaking anything with adding `/priv/ static` back to the .gitignore. However that all seems to be working so this is the logical next step.

Remove hardcoded url from twitter card endpoint

---

lib/tilex/integrations.ex
lib/tilex/slack.ex
lib/tilex/web/templates/shared/post.html.eex
test/features/developer_creates_post_test.exs

Fixing some random warnings and deprecations:
```
warning: variable "post" is unused
lib/tilex/slack.ex:7
warning: clauses for the same def should be grouped together, def notify/2 was previously defined (lib/tilex/integrations.ex:5)
lib/tilex/integrations.ex:27
warning: unexpected beginning of EEx tag "<%=" on end of expression "<%= end %>", please remove "=" accordingly
lib/tilex/web/templates/shared/post.html.eex:19
warning: function Tilex.Router.Helpers.post_url/3 is undefined (module Tilex.Router.Helpers is not available)
lib/tilex/integrations.ex:21
19:29:45.050 [warn] Warning: No valid AppSignal configuration found, continuing with AppSignal metrics disabled.
warning: unused alias Endpoint
test/features/developer_creates_post_test.exs:12
```

Fix warnings

---

config/config.exs
config/test.exs

This moves a timeout extension I added to fix a broken build from all configuration to just the test environment.

Extend HTTPoison timeout in test

---

lib/tilex/web/templates/feed/index.xml.eex

I started using [Reeder](http://reederapp.com/mac/) and noticed you didn't have an author tag.  Finally had an excuse to contribute 😄 .
Atom specification requires email addresses to be supplied when
using `<author>`. Use Dublin Core `<dc:creator>` instead. Replace
`&` with `and` for proper rss validation.
If you don't mind having your email addresses in the rss feed we can use:
```
<author>
<name> <%= post.developer.name %> </name>
<email> <%= post.developer.email %> </email>
</author>
```
I'm assuming name and email exist due to their presence in `validate_required`.

Add author/creator to rss feed

---

app.json

Currently the review apps post show pages are broken. They blow up because they are missing the Canonical Domain.

Require canonical domain for Heroku review apps

---

.iex.exs

#135 overrides a users global iex configuration, which is the fallback if a local one doesn't exist. This imports that file if it exists so that we can still have our global settings.

Import global iex config when available

---

config/config.exs

Currently, likes are stored as cookies.  All the cookies are
collectively submitted as one http header.  Once you've made ~162 likes
then the header size for those cookies exceeds the max header size
allowed on the server.  This is also reportedly an issue in some
browsers but has not been encountered.  Chrome and Firefox handle large
headers fine.  Untested on IE.
For now up the header size allowed on the server to 8192.

Increase cookie size to 8192 from default of 4096

---

README.md

Running the tests without ChromeDriver resulted in an error that included:
```
"Looks like you're trying to run an older version of chromedriver. Wallaby needs at least chromedriver 2.30 to run correctly.
```
This fixes that error.

Document ChromeDriver as a dependency

---

assets/brunch-config.js
assets/css/_components.sass
assets/js/post_form.js
assets/package-lock.json
assets/package.json
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/templates/developer/edit.html.eex
lib/tilex_web/templates/post/edit.html.eex
lib/tilex_web/templates/post/form.html.eex
lib/tilex_web/templates/post/new.html.eex
priv/repo/migrations/20170823194255_update_text_editor_on_developers.exs
test/features/developer_edits_profile_test.exs
test/features/visitor_searches_posts_test.exs

Closes #68 
The name of the branch is a bit misleading as we are now using CodeMirror instead of Ace. The reason for the change is that CodeMirror allows integrating with the brunch pipeline without including a ton of files into the project as the Ace editor does.

Developer selects Code Editor / Vim

---

lib/tilex_web/models/developer.ex
test/models/developer_test.exs

Strips a leading "@" from the twitter handle if present. 
Fixes #157

Strip leading @ from developer twitter handle

---

lib/tilex_web/templates/shared/_elixir.html.eex

My goal here is to ensure it's easy to find our repo from multiple places on the site, and highlight the port specifically on Elixir TILs.

Add a link to our source code on Elixir TILs

---

test/features/visitor_views_post_test.exs

This test was randomly failing 3 out of 5 times I'd run it. 
@jwworth I believe you were also having trouble with this one?
How do we feel about asserting that it still has the `.js-like-action` but refuting that `.js-like-action.liked` exists? I ran this 20 times when I went to lunch and had 0 failures so I believe it fixes the flicker. Its a little wordier but I believe its still explicit enough to represent that "`.js-like-action` should exist but `.js-like-action.liked` should not".

Replace css :not with assert and refute in like post test

---

README.md

The package.json is located in the assets folder

Change to readme for correct installation guidance

---

lib/tilex_web/controllers/auth_controller.ex

This is the first in a series of pull request plan to open, inspired by Elixir Issue #6643.
It's the result of running the Elixir formatter (shipping with Elixir 1.6) against one file in Tilex. Like the Elixir language, I'd like Tilex to conform to the Elixir formatter and growing style consensus of this community. A final step will be enforcing it on each CI build.
I realize this will create churn, but in my opinion it's worth it. These changes can start conversation about our code, and maybe some pull requests against the Elixir formatter itself.
If you're interested in joining in, install Elixir head (with homebrew for example):
```
$  brew install elixir --HEAD
```
And run the formatter on your file of choice:
```
$ mix format lib/tilex/path/to/my_file.ex
```
Elixir Issue #6643 …

Format auth_controller.ex

---

assets/package.json

Adding a description here fixes a warning we were seeing on `npm install`, a documented project setup step.

Add repo & description, silencing install warnings

---

lib/tilex_web/controllers/auth_controller.ex
lib/tilex_web/models/developer.ex
priv/repo/migrations/20171208181757_remove_google_id.exs
priv/repo/seeds.exs
test/controllers/auth_controller_test.exs
test/support/factory.ex

Removes a detail returned from Google that we don't currently use.

Remove unused Google ID from developer

---

assets/brunch-config.js
assets/package-lock.json
assets/package.json

This might fix https://github.com/hashrocket/tilex/issues/155
This is actually an upstream issue related to babel-brunch 6.0.6 using babel-preset-es2016 as a dev dependency if you look at the current package-lock.json in the project.
It seems babel-brunch 6.1.0 uses the preferred dependency of babel-preset-env and none of the yearly presets

update babel-brunch which uses preferred babel-preset-env

---

.circleci/config.yml
config/test.exs
test/features/developer_creates_post_test.exs

These are the the same changes as #263, but without autoformatter alterations.

Enable parallel testing on CI #2

---

.env.example
README.md
config/config.exs
lib/tilex_web/controllers/auth_controller.ex
test/controllers/auth_controller_test.exs

Provide a comma separated list of author emails to allow guests
to post. Refactor authentication error to handle the case when name is
not supplied in the profile since it's never guaranteed to be present.  See  [here]( https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo).
Bit tired so may have missed something.  I'll look over it again tomorrow.

Add guest authoring feature

---

test/controllers/auth_controller_test.exs

This autoformats a new test case with the Elixir 1.6 formatter. Previously our
CI wasn't set up to test forked PR's, allowing this unformatted change onto the
master branch. That setting has been changed and future contributors will be
notified earlier if their code requires formatting.

Format new test case

---

lib/tilex_web/controllers/feed_controller.ex
lib/tilex_web/templates/feed/index.xml.eex

This adds the channel name (`#elixir`) to the title of each RSS feed article.
See #283.

Add Channel to RSS Feed

---

lib/tilex_web/controllers/post_controller.ex
test/controllers/post_controller_test.exs

This change fixes the following issue:
Setup: Visit https://til.hashrocket.com/?page=a
Pagination parameter is ignored
500
This implementation returns the first page when a pagination parameter that cannot be cast to an integer (i.e. "a") is passed, the same thing we do when no pagination parameter is passed.

Robust pagination params

---

lib/tilex_web/controllers/post_controller.ex
test/controllers/post_controller_test.exs

This change passes a string as a parameter in test, making the test more realistic. It also takes advantage of pattern matching in the new function.
h/t @tmock12

Page parameter refactor

---

lib/tilex_web/views/layout_view.ex

`value` is unused, so I got a warning 😄 :  
```shell
warning: variable "value" is unused
lib/tilex_web/views/layout_view.ex:53
```

Fix deprecation warning of unused variable in layout view

---

mix.exs

When we tried out Tilex by deploying it to heroku, the Slack integration did not work. The reason was that posting to Slack depends on `httpoison`, which was not pulled into the build.
`httpoison` is not installed, because it's only an implicit dependency via Wallaby. Wallaby is an [`only: :test`][wallaby] dependency which does not get installed by the [heroku buildpack][].
Deploying a build to Heroku should include the `httpoison` dependency, which is needed to post to the Slack endpoint. This PR accomplishes this by adding httpoison to `mix.exs`, using the version already included in `mix.lock`.
[wallaby]: https://github.com/hashrocket/tilex/blob/a45d0ba3b980a59ed8bfe7d2c1993bfc868a7d1d/mix.exs#L56
[heroku buildpack]: https://github.com/HashNuke/heroku-buildpack-elixir/blob/aea1c4953de03 …

Add httpoison as explicit dependency

---

config/dev.exs

A url configuration for the database overrides the component configurations.  When the url is nil or empty string, the component configurations will be in effect.

Override default dev db settings with DATABASE_URL

---

config/config.exs
lib/tilex_web/templates/error/404.html.eex
lib/tilex_web/templates/error/500.html.eex
lib/tilex_web/views/layout_view.ex

This PR fixes the issue described in #302. It reverts `render_errors` to how it worked before 1a222b9, while keeping the look and feel of the templates introduced in that commit, outside of a layout.
My goal was to keep the templates simple-- there may be more lines of markup we can remove.

Add 404 and 500 templates outside the layouts

---

Makefile
README.md

Make is a flexible tool for common tasks like development ones and it makes the setup/start local application tech agnostic so easier to jump between different projects.
```shell
$ make
help:                          Shows this help.
outdated:                      Shows outdated packages.
setup:                         Runs the project setup.
server:                        Starts the server.
test:                          Tests the project.
```
I got the `help` task idea from this gist: https://gist.github.com/prwhite/8168133

Add Makefile for common dev tasks

---

config/dev.exs

Most likely folders were changed during Phoenix upgrade.

Typo fix in live_reload patterns

---

lib/tilex_web/router.ex

This is a very minor one, but in any case... I think it's a good practice to put catch-any routes to the bottom, b/c in other case it's very easy to forget about it and put a new route bellow catch-any (there it will never work).  
I faced this issue during adding some additional features.

Catch-any route should be last

---

lib/tilex/page_views_report.ex

I was attempting to view the page reports locally but ran into a couple of bugs. 
I had no data from the week before, and we were trying to call `hd/1` on an empty list which returns an `ArgumentError`. Using `List.first/1` will fix that from happening. However, then I was passing nil to `day_output/1` and it wouldn't match. So I added a `No data available` catch function for nil. 
I also made a few other optimizations that i noticed such as using Stream to reduce iterations and `Kernel.match?/2` to remove unnecessary variable bindings.

Page views report missing data

---

.tool-versions
Makefile
elixir_buildpack.config
lib/mix/tasks/tilex/hdb.ex
lib/mix/tasks/tilex/page_views.ex
lib/tilex/stats.ex
lib/tilex_web/templates/layout/app.html.eex
lib/tilex_web/templates/stats/developer.html.eex
mix.exs
test/features/developer_views_stats_test.exs
test/features/visitor_views_post_test.exs

```shell
warning: unused import Mix.Ecto
lib/mix/tasks/tilex/page_views.ex:3
warning: variable "posts_by_channels_count" does not exist and is being expanded to "posts_by_channels_count()", please use parentheses to remove the ambiguity or change the variable name
lib/tilex/stats.ex:40
warning: variable "posts_by_developers_count" does not exist and is being expanded to "posts_by_developers_count()", please use parentheses to remove the ambiguity or change the variable name
lib/tilex/stats.ex:41
warning: variable "developers_count" does not exist and is being expanded to "developers_count()", please use parentheses to remove the ambiguity or change the variable name
lib/tilex/stats.ex:42
warning: variable "most_liked_posts" does not exist and is being expanded to "most_liked_posts()", …
```

 👕 Remove elixir warnings

---

lib/mix/tasks/deploy.ex

```shell
➜  tilex git:(master) mix deploy
Compiling 1 file (.ex)
** (RuntimeError) Unsupported environment, try one of these: ["staging", "production"]
lib/mix/tasks/deploy.ex:15: Mix.Tasks.Deploy.run/1
(mix) lib/mix/task.ex:314: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
(elixir) lib/code.ex:677: Code.require_file/2
```

🎨  Show deployable envs when deploy task has invalid args

---

lib/tilex_web/controllers/post_controller.ex
test/features/admin_edits_post_test.exs
test/support/pages/post_form.ex

Pass a variable that is needed to template

---

.circleci/config.yml
lib/tilex/notifications/notifications.ex

WHAT IT DOES:
Schedules the page views report notifier to be run every Monday at 9AM for whatever timezone you have set (or falls back to Chicago).

Schedule page report notifier every Monday at 9AM

---

mix.exs
mix.lock

Updates wallaby to 0.22.0
I had some crazy chromedriver bugs spewing all over my terminal that were fixed in a newer version of Wallaby.

Update wallaby to 0.22.0

---

lib/tilex/notifications/notifications.ex

A few people ran into an issue when they started their app and it wasn't immediately clear that they were missing a timezone. Perhaps a better runtime error message will help? 
BEFORE:
```terminal
** (Mix) Could not start application tilex: Tilex.start(:normal, []) returned an error: shutdown: failed to start child: Tilex.Notifications
** (EXIT) an exception was raised:
** (ArgumentError) argument error
:erlang.send_after({:error, :invalid_date}, Tilex.Notifications, :generate_page_views_report)
(tilex) lib/tilex/notifications/notifications.ex:107: Tilex.Notifications.schedule_report/0
(tilex) lib/tilex/notifications/notifications.ex:37: Tilex.Notifications.init/1
(stdlib) gen_server.erl:374: :gen_server.init_it/2
(stdlib) gen_server.erl:342: :gen_server.init_it/6
(stdlib) …
```

Add better runtime error for invalid time zone

---

config/config.exs
lib/tilex/auth/guardian.ex
lib/tilex_web/controllers/auth_controller.ex
lib/tilex_web/controllers/developer_controller.ex
lib/tilex_web/controllers/stats_controller.ex
lib/tilex_web/controllers/test/auth_controller.ex
lib/tilex_web/router.ex
test/controllers/stats_controller_test.exs

Fun story, I'm in the process of making some upgrades to the Guardian configuration and I happened to notice we are supposed to be authenticating the developer stats page? but never did...
This PR contains a namespace for Guardian under Auth and more importantly we are now authenticating the developer stats page and have a spec for it.

Authenticate stats

---

lib/tilex/auth/error_handler.ex
lib/tilex_web/router.ex

I'm hoping adding an error_handler here will either fix or give us further insight into the error @jbranchaud is having. This should fix where the current stack trace is blowing up on. 
```
`error_handler` not set in Guardian pipeline
(guardian) lib/guardian/plug/pipeline.ex:233: Guardian.Plug.Pipeline.raise_error/1
(guardian) lib/guardian/plug/verify_session.ex:67: Guardian.Plug.VerifySession.verify_session/2
```

Add error handler for Guardian plug pipeline

---

.env.example
assets/package-lock.json
assets/package.json
assets/webpack.config.js

| Environment | Before | After | Reduction |
| --- | --- | --- | --- |
| Local | 1.7M | 568KB | 67% |
| Staging | 899KB | 344KB | 61% |
I got the idea from production audition:
So I configured `webpack` to compress the files for us. By the way `phoenix` is already configured to try to serve `.gz` files if present on the directory.
no `.gz` files on the `priv/static/` folder structure:
new compressed `.gz` files on the `priv/static/` folder structure:

Gzip static files

---

compile

While doing something totally unrelated, I noticed we weren't serving fingerprinted assets (css and JS) in production. This fixes that. 
You can see on this PRs review app the assets are now properly fingerprinted.

Serve fingerprinted assets

---

mix.exs
mix.lock

It had been locked down to Github since summer of 2017 😄 .

Use earmark 1.3.2 rather than github reference

---

lib/tilex/notifications/notifiers/slack.ex
mix.exs

Given this was the only place we are using HTTPoision, I see no reason not to just use Erlangs built in httpc. IMHO the more dependencies we can remove the better as it reduces potential security intrusions. 
Unfortunately Wallaby still relies on it, but at least we won't.

Replace httpoison with httpc

---

assets/package-lock.json

This updates Tar and changes npm registry links to https, so I'm hoping it will fix the GitHub vulnerability warning...

Minor JS upgrades and use https for npm registry

---

lib/tilex_web/templates/error/404.html.eex
lib/tilex_web/templates/error/500.html.eex
lib/tilex_web/templates/layout/app.html.eex

Google fonts now supports `&display=swap` which should help out performance. This is actually the default when you copy directly from Google fonts now.

Add display swap param to google fonts

---

lib/tilex_web/views/shared_view.ex
mix.lock

This should fix issue #435 
`Timezone.convert/2` has better handling of timezone parsing errors and issues with tzdata than `Timezone.get/1` does, so better to just let it do its thing. 
I also bumped tzdata to 0.5.20 which handles that ETS warning people have been reporting when running the specs.

Fix datetime conversion for post template

---

lib/tilex/stats.ex
lib/tilex_web/templates/stats/developer.html.eex
test/features/developer_views_stats_test.exs

This chart was not designed to work with a signed-in developer's ability to change the date ranges. As such, it cannot currently show data to someone who is logged in. Until somebody wants to implement it, we are removing it.

Remove chart that doesn't work in this context

---

.env.example
Makefile
config/test.exs
test/controllers/api/developer_post_controller_test.exs
test/controllers/auth_controller_test.exs
test/controllers/post_controller_test.exs
test/features/admin_edits_post_test.exs
test/features/developer_creates_post_test.exs
test/features/developer_edits_post_test.exs
test/features/developer_signs_out_test.exs
test/features/developer_views_stats_test.exs
test/features/visitor_searches_posts_test.exs
test/features/visitor_views_channel_test.exs
test/features/visitor_views_developer_test.exs
test/features/visitor_views_post_test.exs
test/features/visitor_views_rss_feed_test.exs
test/features/visitor_views_stats_test.exs
test/features/visitor_visits_homepage_test.exs
test/lib/tilex/rate_limiter_test.exs
test/models/channel_test.exs
test/models/developer_test.exs
test/models/post_test.exs
test/views/shared_view_test.exs

This PR reduces the test suite from `63.2 seconds` to `39.7 seconds`
1. Elixir is quite fast so posts are being created with same inserted_at sometimes which causes a feature test on visitor_views_channel to fail as the posts retrieved by the controller are being sorted by inserted_at field.
2. DBConnection.ConnectionError: connection not available and request was dropped from queue. This exception was happening when running mix test in parallel locally with 8 cores, which means max_cases of 16 on ExUnit. The default value is 10 and this commit changes it to 50.
3. The current test suite leave dirty data on the `requests` table when it runs in parallel as there are some feature tests that ends up tracking accesses outside of the Ecto Sandbox process for some tests. So this commit intends …

⚡️ Setup async tests

---

.tool-versions
phoenix_static_buildpack.config

right now the nodejs version is: `Node 6.9.2`
and this PR #440 have an update that demands at least `8.9.0`

⬆️  Bump nodejs to 12.5.0

---

lib/tilex/markdown.ex
test/lib/tilex/markdown_test.exs

relates to this issue but it does not solve it yet: https://github.com/hashrocket/tilex/issues/430

Expand relative markdown links

---

lib/tilex/auth/error_handler.ex
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/controllers/stats_controller.ex
test/lib/tilex/auth/error_handler_test.exs

This PR avoids the infinite loop to root '/' when the session is
invalid.
1. start the app
2. http://localhost:4000/admin
3. authenticate via oauth
4. quits the app
5. advance local time to some years ahead
6. starts the app again
7. visit http://localhost:4000/ to see the infinite redirect loop
```
[info] GET /
[debug] Processing with TilexWeb.PostController.index/2
Parameters: %{}
Pipelines: [:browser, :browser_auth]
[info] Sent 302 in 98ms
[info] GET /
[debug] Processing with TilexWeb.PostController.index/2
Parameters: %{}
Pipelines: [:browser, :browser_auth]
[info] Sent 302 in 512µs
[info] GET /
[debug] Processing with TilexWeb.PostController.index/2
Parameters: %{}
Pipelines: [:browser, :browser_auth]
[info] Sent 302 in 844µs
```
```
[info] GET /
[debug] Processing with …
```

Fix auth expired redirect loop

---

lib/tilex_web/controllers/pixel_controller.ex

Firefox complained about the pixel request missing a response mime type. This PR adds a mime type of a JavaScript file to address this issue.

Fix tracking pixel mime-type

---

config/config.exs
config/dev.exs
config/prod.exs
config/test.exs

> A new `Config` module has been added to Elixir. The previous configuration API, `Mix.Config`, was part of the Mix build tool. But since releases provide runtime configuration and Mix is not included in releases, we ported the `Mix.Config` API to Elixir. In other words, use `Mix.Config` has been soft-deprecated in favor of `import Config`
Read more in the CHANGELOG:
https://github.com/elixir-lang/elixir/blob/v1.9/CHANGELOG.md#configuration-overhaul

[Elixir 1.9] Migrate Mix.Config -> Config

---

lib/tilex/markdown.ex
lib/tilex_web/views/layout_view.ex

This is the warning it cleans up:
```
<no file>:1: deprecation: The string "https://github.com/pragdave/earmark" will be rendered as a link if the option `pure_links` is enabled.
This will be the case by default in version 1.4.
Disable the option explicitly with `false` to avoid this message.
```
You will see it if you run `mix test`

Clean up Earmark warnings

---

Procfile
app.json

Based on:
- https://jclem.net/posts/2019-08-21-observing-phoenix-on-heroku/
- https://github.com/jclem/phoenix-template
To use follow these steps:
1. In one terminal forward the required ports to the your local machine using the following command:
```bash
heroku ps:forward 9001:4369,9000 -a tilex-staging-pr-555
```
2. In another terminal get the `OTP_COOKIE` from the config on the dyno:
```bash
export OTP_COOKIE=$(heroku config -a tilex-staging-pr-555 | grep OTP_COOKIE | sed 's/OTP_COOKIE://' | xargs)
```
3. Then use it to open an `iex` session against the forwarded port on the local machine:
```bash
env ERL_EPMD_PORT=9001 iex --cookie $OTP_COOKIE --name console@127.0.0.1
```
4. Run `:observer` 
```elixir
iex> :observer.start()
```

Support Observer on Heroku

---

config/config.exs
lib/tilex/rate_limiter.ex

This removes the bottleneck of one process serving as a gateway for all `/like` requests and is inspired by Chris McCords' Programming Phoenix >= 1.4:
> “If all requests depend on a single process for caching, said process will become a bottleneck and hurt the user experience.”
&mdash; Excerpt From: Chris McCord, Bruce Tate, José Valim. “Programming Phoenix ≥ 1.4”
Chapter 12: OTP, Section: Designing an Information System with OTP
ETS allows concurrent reads and writes, and is very fast, so it should allow a higher throughput. Also it is good to set an example to other developers from OTP system design perspective.
This PR also introduces a periodical cleanup of the Rate Limiter table to ensure the memory use is in check. It is likely not an issue, since the Rate Limiter is only used for …

Use ETS for Rate Limiter

---

assets/js/tilex.js

A piece of feedback I've heard about TIL is that the "you signed in" flash covers up our very minimal toolbar until you click it, making it hard for new users to know what do do after authentication.
This change fades out the flash after ten seconds.

Hide the flashes after 10 seconds

---

.circleci/config.yml
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/models/post.ex
test/controllers/post_controller_test.exs

Use the authorized `developer_id` and prevent it from being overwritten by user supplied parameters. Also, prevent users from modify the `developer_id`, `likes`, and `max_likes` when updating a post.

Use authorized post parameters

---

lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/models/post.ex

This change refactors our `Post` model changeset from three functions to one shared function, while exercising tighter control over the parameters we pass to the function.
It builds atop #619, keeping the great tests added there.
Our post controller now features a Rails-style strong parameter whitelisting function called `post_params`. The power to choose most of the correct parameters is being given back to the controller.

Refactor Post Actions and Changeset

---

lib/tilex_web/models/post.ex
test/models/post_test.exs

`generate_slug/0` is an important function, used across the app, that has not been tested before. This change wraps it in a simple unit test.

Test and Refactor slug generation

---

lib/tilex/markdown.ex
lib/tilex_web/views/layout_view.ex

Deprecated: https://hexdocs.pm/floki/Floki.html#parse/1
`Floki.parse_fragment` seems to suit our needs.

Replace deprecated `Floki.parse`

---

lib/tilex_web/templates/error/404.html.eex
lib/tilex_web/templates/error/500.html.eex
lib/tilex_web/templates/layout/app.html.eex

See #620 
Per MDN:
The <meta> element declaring the encoding must be inside the <head>
element and within the first 1024 bytes of the HTML as some browsers
only look at those bytes before choosing an encoding.
Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

Move charset to the top of <head>

---

lib/tilex_web/templates/layout/app.html.eex

See #620:
Per MDN:
Omitted or a JavaScript MIME type: This indicates the script is
JavaScript. The HTML5 specification urges authors to omit the attribute
rather than provide a redundant MIME type. In earlier browsers, this
identified the scripting language of the embedded or imported (via the
src attribute) code. JavaScript MIME types are listed in the
specification.
Source:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

Remove redundant MIME type

---

config/test.exs
lib/tilex_web/templates/shared/post.html.eex
lib/tilex_web/views/shared_view.ex
test/views/shared_view_test.exs

See #620.
This change refactors a few tests, in the service of adding a `byline` class and `time` tag to our post partial. Those tags help Safari Reader Mode figure out what's important in a post's HTML. See highlighted copy.

Add Byline and Post Time Tag

---

lib/mix/tasks/tilex/hdb.ex
lib/tilex_web/controllers/stats_controller.ex
priv/repo/migrations/20200518184142_add_index_to_request_time_on_requests.exs
test/features/developer_views_stats_test.exs

Putting an index on the requests table brings the query time down to ~ 200ms in our local database with production data.  Down from 2.5 seconds for 2.5M rows.

Improve stats performance

---

lib/tilex/notifications/notifiers/slack.ex

We are approaching 100 likes on a TIL. We only added Slack emojis up to
100 likes; after that, who knows what will happen?
In the meantime, please STOP liking this post:
https://til.hashrocket.com/posts/2034bed53c-create-new-file-in-vims-file-explorer
This PR solves this very important issue by adding a new realm of Emojis to
achieve, up to 200 likes.

User sees Slack emojis past 100 likes

---

.circleci/config.yml
assets/package-lock.json
assets/package.json

Collect a few noteworthy Dependabot PR commits that upgrade JS dependencies, while closing the original PR's. Also, test our CI test suite, which has been failing of late.
We have uninstalled Dependabot on Tilex. The signal-to-noise ratio was off for a mature project such as this.
`git cherry-pick`

Upgrade JavaScript dependencies

---

assets/css/_layout.scss
lib/tilex_web/templates/layout/app.html.eex

This makes tabbing through the site a little easier. Currently when you visit the home page you have to tab through each til, any links in it, all the buttons, etc. Now when you visit the site and tab navigate, you should tab right through the navigation first. 
There was also an issue with the search, currently it was just width 0, which allowed you tab into it, but you couldn't see what you were doing. Now you can choose to open it (return), or keep tabbing to the next nav item. 
Fixes #641

Site nav enhancements

---

assets/js/tilex.js

Small UX improvement to prevent overlap of site nav links when clicking through. This can be seen when clicking from the about link to the search link - the search input opens behind the "about" pop up.

Site Nav UX

---

assets/js/like.js
lib/tilex_web/templates/layout/app.html.eex

TIL while playing with liveview that [Phoenix.HTML.Tag.csrf_meta_tag/0](https://github.com/phoenixframework/phoenix_html/blob/v2.14.2/lib/phoenix_html/tag.ex#L259)  exists? Rather than maintain our own logic, it may be better to just let Phoenix handle it?

Replace custom meta tag with Phoenix html csrf_meta_tag

---

lib/tilex/markdown.ex
test/lib/tilex/markdown_test.exs

Fix broken markdown when code snippet has `>` operators

---

lib/tilex/pageable.ex
lib/tilex/posts.ex
lib/tilex_web/controllers/api/post_controller.ex
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/router.ex
lib/tilex_web/views/api/developer_post_view.ex
lib/tilex_web/views/api/post_view.ex
test/controllers/api/post_controller_test.exs

Adds the endpoint `/api/recent_posts.json` to fetch the json feed of TIL
* Supports an optional `limit` param for adjusting the number returned - default is 10

feat: add a til posts api endpoint

---

config/config.exs
config/test.exs
lib/test/notifications/notifiers/slack.ex
lib/test/notifications/notifiers/twitter.ex
lib/tilex/notifications/notifications.ex
lib/tilex/notifications/notifiers/notifier.ex
lib/tilex/notifications/notifiers/slack.ex
lib/tilex/notifications/notifiers/twitter.ex
lib/tilex/posts.ex
test/tilex/notifications/notifiers/slack_test.exs

Fix slack notification if post includes double quote

---

lib/tilex/page_views_report.ex
priv/repo/migrations/20220425135720_add_request_time_in_chicago_tz_index_to_requests.exs
priv/repo/migrations/20220429184256_add_request_time_in_application_timezone_index_to_requests.exs

Fixes a timeout on the report query that bubbled up to a `MatchError` in signal. 
This adds a [functional index](https://www.postgresql.org/docs/current/indexes-expressional.html) to `requests.request_time`, which was ultimately used by the left hand side of the [where clause in the report query](https://github.com/hashrocket/tilex/blob/6fe95bba7ddddef7dd138dab654f4052d4e060a5/lib/tilex/page_views_report.ex#L4). 
Before adding the index, we are seeing the following performance for the [report query](https://github.com/hashrocket/tilex/blob/6fe95bba7ddddef7dd138dab654f4052d4e060a5/lib/tilex/page_views_report.ex#L3): 
* **Prod** - `> 30s`
* **Development (with the same database - > 5 million records in the table)** - `~ 10s`. 
After adding the index in this PR, we're seeing the query run in …

fix(appsignal-95): add index for request time in chicago

---

assets/css/_layout.scss
lib/tilex_web/templates/layout/site_nav.html.eex

This would keep the current statistics link in place, and move the admin statistics link to the bottom of the nav if signed in.

Add statistics link when signed in

---

lib/tilex_web/views/layout_view.ex
test/features/visitor_views_post_test.exs

Fix twitter image url due to missing host

---

assets/css/layout.css
config/config.exs
lib/tilex_web/templates/layout/app.html.heex
lib/tilex_web/templates/layout/root.html.heex

* adds 3 new config variables to flag on banners:
* BANNER_IMAGE_SOURCE (this is the one that flips on the banner)
* BANNER_IMAGE_LINK
* BANNER_IMAGE_ALT

feat: banners images can be flagged on with env

---

lib/tilex/tracking.ex
lib/tilex_web/templates/stats/developer.html.eex
test/lib/tilex/tracking_test.exs

Adds the channel name to each item in the `Most Viewed Posts` list on `/developer/statistics`

feat: add channel name to most viewed posts list

---

lib/tilex/pageable.ex
lib/tilex/plug/set_canonical_url.ex
lib/tilex/posts.ex
lib/tilex_web/controllers/api/post_controller.ex
lib/tilex_web/controllers/channel_controller.ex
lib/tilex_web/controllers/developer_controller.ex
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/controllers/sitemap_controller.ex
lib/tilex_web/controllers/stats_controller.ex
lib/tilex_web/router.ex
lib/tilex_web/templates/layout/root.html.heex
lib/tilex_web/templates/sitemap/sitemap.xml.eex
priv/static/robots.txt
test/lib/tilex/plug/set_canonical_url_test.exs

we found so much trash indexed urls in the google search console that we decided to review SEO for `tilex` and we come up with this PR. We are expecting to reduce the number of indexed page from 3.5K pages to about 600. That might improve the rank of our posts on search engines in general.
---
| before | after |
| --- | --- |
| <img width="891" alt="image" src="https://user-images.githubusercontent.com/1071893/207426668-f7b54092-facf-410a-8f31-1475ffa45154.png"> | |
| <img width="931" alt="image" src="https://user-images.githubusercontent.com/1071893/207426744-a13c7751-52cc-44bd-8c29-98a47e3509ea.png"> | |
| <img width="910" alt="image" src="https://user-images.githubusercontent.com/1071893/207427056-ebcc60da-3b0d-4833-b2b7-92e401213e14.png"> | |
https://search.google.com/

SEO improvements

---

lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/templates/layout/root.html.heex
lib/tilex_web/views/layout_view.ex
lib/tilex_web/views/structured_data_view.ex

structured data helps search engines like google to display better results to the final user
- [Structured Data Doc](https://developers.google.com/search/docs/appearance/structured-data/article)
- [Schema Validator](https://validator.schema.org/)
- [Rich Results Test](https://search.google.com/test/rich-results)
---

Add structured data for Rich Search 

---

lib/tilex_web/templates/layout/root.html.heex
lib/tilex_web/views/layout_view.ex
lib/tilex_web/views/structured_data_view.ex
test/views/structured_data_view_test.exs

There's an issue with some TIL posts which has some content like `<script>` and as the `articleBody` was not sanitized properly that tag was early closing that `ld+json` script for the structured data. My goal for now is just remove that `articleBody` also because I think that's not needed for `BlogPosting`. I'm going to keep an eye on google indexing and we might come back to that later on with a proper `script` escaping if needed.

Remove article body from structured data

---

lib/tilex/blog/post_scrubber.ex
lib/tilex/markdown.ex
test/lib/tilex/markdown_test.exs

Revert the post scrubber back from `html5` to a custom scrubber that is a variation of the [markdown scrubber from html_sanitize_ex](https://github.com/rrrene/html_sanitize_ex/blob/master/lib/html_sanitize_ex/scrubber/markdown_html.ex).
in addition -
* add a test that covers - inputs and forms should NOT be allowed in markdown content
* add a test that covers - inputs, forms, and html5 tags should be allowed within codeblocks in markdown content

fix(markdown): convert markdown to html, then sanitize
