hashrocket/tilex

CONTRIBUTING.md

This is what potential contributors will be prompted to read before
submitting a pull request --
https://github.com/blog/1184-contributing-guidelines

Add a CONTRIBUTING.md file for github

---

lib/tilex/plug/basic_auth.ex
web/router.ex

Hey @jwworth, I moved the conditional logic for BasicAuth into a custom plug. It helps keep the router clean. What do you think?

Move basic auth conditional logic to plug

---

test/features/visitor_views_post_test.exs
web/templates/post/show.html.eex
web/templates/shared/_elixir.html.eex
web/templates/shared/_rails.html.eex
web/templates/shared/_ruby.html.eex
web/templates/shared/_sql.html.eex
web/templates/shared/_vim.html.eex
web/templates/shared/post.html.eex
web/views/post_view.ex

This adds marketing content to the bottom of each post show page, when we have chosen to highlight our expertise in a given channel.

Add marketing copy, when appropriate

---

test/features/visitor_searches_posts.exs
web/channels/post_channel.ex
web/channels/user_socket.ex
web/static/js/post_search.js
web/static/js/tilex.js
web/templates/layout/app.html.eex
web/templates/post/search_results.html.eex
web/views/post_view.ex

Forgot to commit this last week.
Probably totally overkill to use websockets for this search function but I wanted to explore what it could look like. 
Notes as I explore:
- currently I'm using just a simple `ilike` query, we would eventually need the full weighted query as it currently exists in rails world (https://github.com/hashrocket/hr-til/blob/master/app/models/post.rb#L115)

WIPish - Visitor searches post titles

---

lib/tilex/posts.ex
test/features/visitor_views_channel_test.exs
test/features/visitor_visits_homepage_test.exs
test/support/factory.ex
web/controllers/channel_controller.ex
web/controllers/post_controller.ex
web/templates/channel/show.html.eex
web/templates/post/index.html.eex
web/templates/shared/_pagination.html.eex
web/templates/shared/_posts_list.html.eex

Pushing Ecto querying down to the Tilex.Posts module but not entirely happy cause I can't compose ecto queries.
There's probably some good refactoring to do in that module but whatev tests pass pagination in effect.

Paginate homepage and channels at 50 posts

---

lib/test/slack.ex
lib/test/twitter.ex
web/channels/post_channel.ex
web/controllers/auth_controller.ex

This remedies a few helpful warnings that Elixir provides before compilation.

Cleanup warnings

---

test/features/developer_creates_post_test.exs
test/support/pages/create_post_page.ex
test/support/pages/index_page.ex
test/support/pages/navigation.ex
test/support/pages/post_show_page.ex

This is an experiment in using Page Modules (ala Page Objects) for feature tests. What do y'all think?

Add Page Modules concept for integration tests

---

test/features/developer_creates_post_test.exs
test/features/developer_edits_post_test.exs
test/support/pages/create_post_page.ex
test/support/pages/post_form.ex
web/channels/text_converter_channel.ex
web/channels/user_socket.ex
web/models/post.ex
web/static/js/post_form.js
web/static/js/text_conversion.js
web/static/js/tilex.js
web/templates/post/form.html.eex

Live Preview of markdown for editing and creating posts.

Developer views post preview

---

web/controllers/post_controller.ex

Fix syntax warnings in post controller

---

lib/tilex/stats.ex
test/features/visitor_views_stats_test.exs
web/templates/stats/index.html.eex

Hot posts query based on @jbranchaud's [sllides](https://raw.githubusercontent.com/jbranchaud/talks/master/embrace-the-database-with-ecto-2017-03-02/embrace-the-database-with-ecto-2017-03-02.md)

Visitor views hot posts

---

test/controllers/auth_controller_test.exs

Use `get_flash` instead of custom `flash_info`.

Use get_flash instead of custom helper

---

lib/tilex/slack.ex

Add channel hashtag to Slack post

---

test/features/visit_views_rss_feed_test.exs
web/controllers/post_controller.ex

Support legacy Atom query parameter

---

lib/tilex/slack.ex
test/lib/tilex/slack_test.exs

Posts contain channel name, not Twitter hashtag

---

test/features/robot_sees_sitemap.exs
web/controllers/sitemap_controller.ex
web/router.ex
web/templates/sitemap/sitemap.xml.eex
web/views/sitemap_view.ex

Add a sitemap.  It doesn't hurt.

Create a sitemap

---

web/controllers/sitemap_controller.ex

Fix unnecessary conn assignment in sitemap controller

---

mix.exs
mix.lock

https://github.com/pragdave/earmark/issues/150

Upgrade Earmark to avoid logging bugs

---

config/prod.exs
web/static/js/app.js
web/templates/layout/app.html.eex

Only use Google analytics when key is set

---

web/controllers/post_controller.ex

Just doing some cleanup of module calls that we don't need.

Remove unnecessary module calls from post controller

---

app.json

Right now the review apps are broken on Heroku. Hoping running these fix them...
Update - "View deployment" now links to a successfully migrated review app on Heroku.

Migrate and seed database on heroku review app

---

lib/tilex/web/templates/shared/_elixir.html.eex
lib/tilex/web/templates/shared/_rails.html.eex

Link to marketing pages

---

.env.example
config/dev.exs
config/prod.exs
config/test.exs
lib/tilex/twitter.ex
lib/tilex/web/models/developer.ex
lib/tilex/web/templates/shared/post.html.eex
priv/repo/migrations/20170726192554_remove_default_from_twitter_handle_column.exs

Remove the default twitter handle from the db and 
instead set the default twitter handle as an env var

Provide default twitter handle

---

assets/css/_components.sass
assets/js/app.js
assets/js/post_form.js
assets/js/syntax_label.js
assets/js/tilex.js

User sees code snippet headers

---

.iex.exs

This file loads our most common aliases into your IEx session. I'd love to see other proposed additions for making a great console experience. h/t @codyjroberts

Add IEX config file

---

.travis.yml
lib/tilex/posts.ex

Weight search results by title and body

---

.credo.exs
.iex.exs
.travis.yml
README.md
lib/guardian_serializer.ex
lib/mix/tasks/ecto.twiki.ex
lib/tilex/cache.ex
lib/tilex/integrations.ex
lib/tilex/markdown.ex
lib/tilex/posts.ex
lib/tilex/slack.ex
lib/tilex/stats.ex
lib/tilex_web/controllers/api/developer_post_controller.ex
lib/tilex_web/controllers/auth_controller.ex
lib/tilex_web/controllers/channel_controller.ex
lib/tilex_web/controllers/developer_controller.ex
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/models/developer.ex
lib/tilex_web/models/post.ex

This finishes our implementation of static analysis with [Credo](https://github.com/rrrene/credo), by doing the following:
- Ignoring checks that don't match our style goals
- Fixing all remaining checks
- Running Credo on every CI build
It includes a few additions to our IEx config that I discovered while iterating over the Credo issues.

Implement credo

---

lib/tilex_web/models/developer.ex

Autoformat the developer model

---

test/support/test_helpers.ex

Autoformat the test helper

---

lib/tilex_web/controllers/channel_controller.ex

Format the channel controller

---

test/controllers/post_controller_test.exs

Autoformat the post controller test

---

lib/tilex_web/models/channel.ex

Format the channel model

---

test/lib/tilex/markdown_test.exs
test/support/integration_case.ex

Format the integration helper and markdown test

---

test/views/error_view_test.exs

Format the error view test

---

lib/tilex_web/views/web_manifest_view.ex

Format the web manifest

---

lib/tilex_web/controllers/post_controller.ex

Format the post controller

---

test/support/pages/create_post_page.ex
test/support/pages/index_page.ex
test/support/pages/post_form.ex
test/support/pages/post_show_page.ex

Autoformat all the page objects

---

lib/tilex_web/router.ex

Format the router

---

lib/tilex_web/views/error_helpers.ex
lib/tilex_web/views/error_view.ex
lib/tilex_web/views/sitemap_view.ex

Format all views

---

lib/tilex_web/controllers/developer_controller.ex

Format the developer's controller

---

test/test_helper.exs

Format the test helper

---

.circleci/config.yml
CONTRIBUTING.md

This pull request is not meant to be merged now. It is a placeholder while we bring our codebase in line with the Elixir 1.6 formatter. When that happens and we rebase the branch from master, this should be a passing build.

Run mix format on every CI build

---

lib/tilex_web/models/post.ex
lib/tilex_web/templates/layout/app.html.eex
lib/tilex_web/views/layout_view.ex

Add a unique Twitter title for each post

---

lib/tilex_web/views/layout_view.ex
test/features/visitor_views_post_test.exs

For real this time with a TEST to make sure it works and doesn't break.
Sorry to push untested code!  Happy Birthday!!  🍰 🍰 🍰

Remove markdown from twitter description

---

README.md

Omniauth -> Ueberauth in README

---

assets/js/post_form.js

Fix preview titles

---

app.json

This will allow our review apps to build with required env vars.

Inherit display TZ from staging app

---

.circleci/config.yml
.tool-versions
Procfile
elixir_buildpack.config
mix.exs

Upgrade elixir 1.8

---

test/controllers/api/developer_post_controller_test.exs

Store posts with timestamp in developer post controller test

---

.circleci/config.yml

This removes a few redundant steps, and reorganizes others in a more logical way.

Clean up Circle CI config

---

.credo.exs
test/support/factory.ex
test/support/model_case.ex
test/support/pages/post_show_page.ex
test/support/test_helpers.ex

This adds the latest `.credo.exs` file, and makes a few changes to comply with the checks.

Update credo config and refactor code to comply

---

.github/issue_template.md

This should be an h3 header like every other step, and it should prompt the user to add numbered steps.

Correct issue template 'steps'

---

assets/css/_layout.sass
lib/tilex_web/templates/layout/app.html.eex

Co-authored-by: Chris Erin <chris.erin@hashrocket.com>

Visitors see ACR banner

---

assets/package-lock.json

Fixed using `npm audit fix`.
Before
After

Fix node modules security vulnerabilities

---

lib/tilex/markdown.ex
test/lib/tilex/markdown_test.exs

Restore autolink functionality

---

.env.example

This is step one in a process of cleaning up our environment(al) variables.

Organize env variables

---

README.md

I'd like to direct attention to the many people who have contributed to Tilex.

Recognize Tilex contributors

---

lib/tilex_web/templates/shared/_elixir.html.eex

We have talked about updating this copy for a long time. It's a little out of date. This is the first draft and I'd love to get feedback. Did I hit the right tone? Is it persuasive? Are emojis in an HTML file a good idea?
Here's what it looks like (Firefox):

Update Elixir marketing footer

---

CONTRIBUTING.md
README.md
USAGE.md

These docs needed to be refreshed.

Update developer docs

---

lib/tilex_web/templates/error/404.html.eex
lib/tilex_web/templates/error/500.html.eex
lib/tilex_web/templates/shared/post.html.eex
test/features/visitor_searches_posts_test.exs

Remove a <section> that seems unnecessary

---

lib/tilex_web/templates/shared/_javascript.html.eex
lib/tilex_web/templates/shared/_rails.html.eex
lib/tilex_web/templates/shared/_ruby.html.eex
lib/tilex_web/templates/shared/_sql.html.eex
lib/tilex_web/templates/shared/_vim.html.eex

Our most-posted channels are vim, command-line, elixir, ruby, javascript, sql, workflow, rails, git, and react. I'd love to have a footer for each, but a few of them, like 'workflow', don't lend themselve to marketing. Of those that remain, this is my attempt to correct misinformation and make the text a little more compelling, when possible.

Edit and cleanup footers

---

lib/tilex_web/templates/layout/app.html.eex

Getting these tags right makes our site look better on various social media platforms. I'm roughly following the guidance described here:
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

User sees richer post previews on social media

---

README.md

Adding two of our marketing channels to the project documentation.

User sees social links

---

assets/css/_hiring_banner.scss
assets/css/_layout.scss
assets/static/images/right-arrow.svg
lib/tilex_web/templates/error/404.html.eex
lib/tilex_web/templates/error/500.html.eex
lib/tilex_web/templates/shared/_hiring_banner.html.eex

Fix width for hiring banner to avoid safari issue

---

lib/tilex/plug/request_rejector.ex
lib/tilex_web/router.ex
test/lib/tilex/plug/request_rejector_test.exs

Reject requests from forbidden paths

---

lib/tilex/notifications/notifications.ex
test/lib/tilex/notifications/notifications_test.exs

Schedule Next Report Notification

---

assets/css/_layout.scss
lib/tilex/posts.ex
lib/tilex_web/controllers/channel_controller.ex
lib/tilex_web/controllers/post_controller.ex
lib/tilex_web/router.ex
lib/tilex_web/templates/channel/show.html.eex
lib/tilex_web/views/channel_view.ex
test/features/visitor_views_post_test.exs

Provides the ability to find random posts by a specific channel

Random by channel

---

lib/tilex_web/templates/layout/site_nav.html.eex

Add admin statistics icon back

---

lib/tilex_web/views/layout_view.ex
test/features/visitor_views_error_page_test.exs
test/features/visitor_visits_homepage_test.exs

Fix page title for home page and add test

---

assets/css/components.css

Updates `css` for posts to make the background a solid color and add a box shadow

feat(post): add solid background color and box shadow

---

assets/css/components.css
lib/tilex_web/templates/post/show.html.eex

https://www.pivotaltracker.com/story/show/163494296

feat(til): add CTA to til show
